require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "db/schema.rb"
    - "bin/**/*"
    - "config/**/*"
    - "Gemfile"
    - "Rakefile"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"

Rails:
  Enabled: true

RSpec/MultipleExpectations:
  Max: 3

RSpec/ExampleLength:
  Max: 10
